"""posts table

Revision ID: be406308ce67
Revises: 311b8fa0bcb7
Create Date: 2022-02-02 22:51:21.895293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be406308ce67'
down_revision = '311b8fa0bcb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('creation', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_creation'), 'post', ['creation'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_creation'), table_name='post')
    op.drop_column('post', 'creation')
    # ### end Alembic commands ###
